# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
#source 'https://github.com/CocoaPods/Specs.git'

target 'SDKDemo' do

  use_frameworks!


  pod 'Masonry'
  

  pod 'Protobuf', '~> 3.14.0'
  pod 'YYKit'
  pod 'SAMKeychain'
  pod 'Realm'
  
end
