# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
#source 'https://github.com/CocoaPods/Specs.git'

target 'SDKDemo' do

  use_frameworks!


  pod 'Masonry'
  
 pod 'EABluetooth', :git =>  'https://github.com/EastApex/EASDKTool_iOS.git'

end
