# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EASDKDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
 use_frameworks!


  pod 'Masonry'
  

  pod 'Protobuf', '~> 3.14.0'
  pod 'YYKit'
  pod 'SAMKeychain'
  pod 'Realm'

end
